{% set name = "vessel-express-napari" %}
{% set version = "0.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/vessel-express-napari-{{ version }}.tar.gz
  sha256: 0d3312dc17de487b1d29485f3eaf92b935da3e0298b746e104d1b323316f04b5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - aicssegmentation
    - itk
    - napari-plugin-engine >=0.1.4
    - napari
    - numpy
    - python >=3.7
    - qtpy
    - scikit-image
    - tifffile

test:
  imports:
    - vessel_express
  commands:
    - pip list
    # - pip check  # itk
  requires:
    - pip

about:
  home: https://github.com/MMV-Lab/vessel-express-napari
  summary: A simple plugin for 3D vessel segmentation
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
